/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcialuno;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daiki
 */
public class Vista extends javax.swing.JFrame {

   
    DefaultTableModel t_vehiculo;
    
    public Vista() {
        initComponents();
        
        t_vehiculo = new DefaultTableModel ();
        String encabezado[]={"Tipo de Vehiculo","Subtipo","Numero de Serie","Marca","Modelo"};
        t_vehiculo.setColumnIdentifiers(encabezado);
        this.tbl_vehiculo.setModel(t_vehiculo);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vehiculo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        subtipoCombo = new javax.swing.JComboBox<>();
        agregarBtn = new javax.swing.JButton();
        motoButton = new javax.swing.JRadioButton();
        carroButton = new javax.swing.JRadioButton();
        avionButton = new javax.swing.JRadioButton();
        heliButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numeroserieTxt = new javax.swing.JTextField();
        marcaTxt = new javax.swing.JTextField();
        modeloTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_vehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_vehiculo);

        jTabbedPane1.addTab("Vehiculos", jScrollPane1);

        jLabel2.setText("Tipo de Vehiculo");

        subtipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aereo", "Terrestre" }));
        subtipoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtipoComboActionPerformed(evt);
            }
        });

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(motoButton);
        motoButton.setText("Moto");
        motoButton.setEnabled(false);
        motoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(carroButton);
        carroButton.setText("Automovil");
        carroButton.setEnabled(false);
        carroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carroButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(avionButton);
        avionButton.setText("Avion");
        avionButton.setEnabled(false);
        avionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(heliButton);
        heliButton.setText("Helicoptero");
        heliButton.setEnabled(false);
        heliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Marca");

        jLabel3.setText("Numero de Serie");

        jLabel4.setText("Modelo");

        numeroserieTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroserieTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(subtipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(motoButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(carroButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(avionButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(heliButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroserieTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(marcaTxt)
                            .addComponent(modeloTxt))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarBtn)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subtipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motoButton)
                    .addComponent(carroButton)
                    .addComponent(avionButton)
                    .addComponent(heliButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroserieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(marcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(agregarBtn)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subtipoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtipoComboActionPerformed
       String vehiculo;
       vehiculo = (String) subtipoCombo.getSelectedItem();
       if (vehiculo == "Terrestre"){
           
       carroButton.setEnabled(true);
       motoButton.setEnabled(true);
       avionButton.setEnabled(false);
       heliButton.setEnabled(false);
       
       }else if (vehiculo == "Aereo"){
           
       carroButton.setEnabled(false);
       motoButton.setEnabled(false);
       avionButton.setEnabled(true);
       heliButton.setEnabled(true);
       
       }
    }//GEN-LAST:event_subtipoComboActionPerformed

    private void motoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motoButtonActionPerformed

    private void avionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avionButtonActionPerformed

    private void carroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carroButtonActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
    String datos[] = new String[5];
        datos[0] = (String) subtipoCombo.getSelectedItem();
        if (datos[0]=="Aereo")
        {
            if (avionButton.isSelected()){
                
            datos[1] = avionButton.getText();
            
            } else {
                
                datos[1] = heliButton.getText();
            }
            
        }
               if (datos[0]=="Terrestre")
        {
            if (carroButton.isSelected()){
                
            datos[1] = carroButton.getText();
            
            } else {
                
                datos[1] = motoButton.getText();
            }
             
        }
        datos[2] = numeroserieTxt.getText();
        datos[3] = marcaTxt.getText();
        datos[4] = modeloTxt.getText();  
        t_vehiculo.addRow(datos);
        JOptionPane.showMessageDialog(rootPane, "Ingreso Correcto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
       
                // TODO add your handling code here:
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void numeroserieTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroserieTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroserieTxtActionPerformed

    private void heliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JRadioButton avionButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton carroButton;
    private javax.swing.JRadioButton heliButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JRadioButton motoButton;
    private javax.swing.JTextField numeroserieTxt;
    private javax.swing.JComboBox<String> subtipoCombo;
    private javax.swing.JTable tbl_vehiculo;
    // End of variables declaration//GEN-END:variables
}
